# Set update schedule for GitHub Actions

version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - type:ci
    # https://til.simonwillison.net/github/dependabot-python-setup
    groups:
      github-actions:
        patterns:
          - '*'
  - package-ecosystem: uv
    directory: /
    schedule:
      interval: weekly
    labels:
      - type:dependency
    versioning-strategy: increase-if-necessary
    ignore:
      - dependency-name: etl-entities
        update-types: [version-update:semver-major]
      - dependency-name: pydantic
        update-types: [version-update:semver-major]
      - dependency-name: pyspark
        update-types: [version-update:semver-major]
      - dependency-name: pandas
        update-types: [version-update:semver-major, version-update:semver-minor]
      - dependency-name: numpy
        update-types: [version-update:semver-major, version-update:semver-minor]
      - dependency-name: pymongo
        update-types: [version-update:semver-major]
      - dependency-name: setuptools
        update-types: [version-update:semver-major]
      - dependency-name: pytest
        update-types: [version-update:semver-major]
      - dependency-name: pytest-rerunfailures
        update-types: [version-update:semver-major]
    # https://til.simonwillison.net/github/dependabot-python-setup
    groups:
      python-packages:
        patterns:
          - '*'
