repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-ast
        priority: 0
      - id: check-case-conflict
        priority: 0
      - id: check-docstring-first
        priority: 0
      - id: check-executables-have-shebangs
        priority: 0
      - id: check-merge-conflict
        priority: 0
      - id: check-toml
        priority: 0
      - id: check-vcs-permalinks
        priority: 0
      - id: name-tests-test
        files: ^tests/(tests_integration|tests_unit)/.*\.py$
        args: [--django]
        priority: 0
      - id: end-of-file-fixer
        exclude: ^(.*/VERSION|tests/resources/.*/.*)$
        priority: 1
      - id: fix-byte-order-marker
        priority: 2
      - id: trailing-whitespace
        priority: 3

  - repo: https://github.com/IamTheFij/docker-pre-commit
    rev: v3.0.1
    hooks:
      - id: docker-compose-check
        priority: 0

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.6
    hooks:
      - id: forbid-tabs
        priority: 0
      - id: remove-tabs
        args: [--whitespaces-count, '2']
        priority: 4
      - id: chmod
        args: ['644']
        exclude_types: [shell]
        exclude: ^(tests/resources/file_df_connection/generate_files\.py)$
        priority: 5
      - id: chmod
        args: ['755']
        types: [shell]
        priority: 5
      - id: chmod
        args: ['755']
        files: ^(tests/resources/file_df_connection/generate_files\.py)$
        priority: 5
      - id: insert-license
        files: .*\.py$
        exclude: ^(setup\.py|conftest\.py|docs/.*\.py|tests/.*\.py)$
        args:
          - --license-filepath
          - .spdx-license-header.txt
          - --allow-past-years
          - --no-extra-eol
        priority: 6

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.3
    hooks:
      - id: codespell
        args: [-w]
        priority: 7

  - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.16.0
    hooks:
      - id: pretty-format-yaml
        args: [--autofix, --indent, '2', --offset, '2']
        priority: 8

  - repo: https://github.com/lovesegfault/beautysh
    rev: v6.4.3
    hooks:
      - id: beautysh
        additional_dependencies: [setuptools]
        priority: 8

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.12.1
    hooks:
      - id: uv-lock
        priority: 8

  - repo: local
    hooks:
      - id: towncrier
        name: towncrier
        entry: towncrier build --draft
        language: system
        types: [markdown]
        pass_filenames: false
        priority: 8

      - id: links2anchors
        name: links2anchors
        entry: python mddocs/scripts/links2anchors.py
        language: system
        types: [markdown]
        pass_filenames: false
        priority: 8

      - id: generate_anchors
        name: generate_anchors
        entry: python mddocs/scripts/generate_anchors.py
        language: system
        types: [markdown]
        pass_filenames: false
        priority: 8

      - id: ruff-format
        name: ruff-format
        language: system
        entry: ruff format .
        types: [python]
        pass_filenames: false
        priority: 8

      - id: ruff-check
        name: ruff-check
        language: system
        entry: ruff check --fix
        types: [python]
        pass_filenames: false
        priority: 9

      - id: mypy
        name: mypy
        entry: python3 -m mypy onetl
        language: system
        types: [python]
        pass_filenames: false
        priority: 10

  - repo: meta
    hooks:
      - id: check-hooks-apply
        priority: 0
      - id: check-useless-excludes
        priority: 0

ci:
  skip:
    - chmod # failing in pre-commit.ci
    - docker-compose-check # cannot run on pre-commit.ci
    - mypy # checked with Github Actions
    - ruff-format # checked with Github Actions
    - ruff-check # checked with Github Actions
    - towncrier # checked with Github Actions
