version: 2

python:
  version: '3.8'
  install:
  - requirements: requirements/requirements.txt
  - requirements: requirements/requirements-docs.txt
  - method: pip
    path: .[ftp, ftps, hdfs, s3, sftp, webdav, spark]
