version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.13"
  jobs:
    post_checkout:
      - git fetch --unshallow || true
    post_create_environment:
      - python -m pip install --exists-action=w --no-cache-dir --no-deps sphinx-plantuml # remove after https://github.com/zqmillet/sphinx-plantuml/pull/4
      - python -m pip install --exists-action=w --no-cache-dir -r requirements/docs.txt
      - python -m pip install --exists-action=w --upgrade --upgrade-strategy only-if-needed --no-cache-dir .[ftp,ftps,hdfs,samba,s3,sftp,webdav,spark]
    post_install:
      # TODO: remove after upgrading autodoc-pydantic to v2
      - python -m pip install --exists-action=w --no-cache-dir "sphinx<8"

# TODO: uncomment after https://github.com/zqmillet/sphinx-plantuml/pull/4
#python:
#  install:
#  - requirements: requirements/docs.txt
#  - method: pip
#    path: .
#    extra_requirements:
#    - ftp
#    - ftps
#    - hdfs
#    - samba
#    - s3
#    - sftp
#    - webdav
#    - spark
