version: 2

mkdocs:
  configuration: mddocs/mkdocs.yml

build:
  os: ubuntu-24.04
  tools:
    python: '3.14'
  jobs:
    post_create_environment:
      - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH python -m pip install uv
    post_install:
      - UV_PROJECT_ENVIRONMENT=$READTHEDOCS_VIRTUALENV_PATH uv sync --no-install-project --extra files --group docs
      - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH python -m pip list -v
    pre_build:
      - python mddocs/scripts/generate_anchors.py
      - python mddocs/scripts/fix_refs.py
      - python mddocs/scripts/links2anchors.py
