# SPDX-FileCopyrightText: 2022-present MTS PJSC
# SPDX-License-Identifier: Apache-2.0
import logging
import time
import warnings
from abc import abstractmethod
from collections.abc import Callable
from contextlib import closing
from enum import Enum, auto
from typing import TYPE_CHECKING, ClassVar, TypeVar

from humanize import naturaldelta

try:
    from pydantic.v1 import Field, SecretStr
except (ImportError, AttributeError):
    from pydantic import Field, SecretStr  # type: ignore[no-redef, assignment]

from onetl._metrics.command import SparkCommandMetrics
from onetl._util.java import get_java_gateway
from onetl._util.spark import (
    estimate_dataframe_size,
    get_spark_version,
    override_job_description,
    stringify,
)
from onetl._util.sql import clear_statement
from onetl._util.version import Version
from onetl.connection.db_connection.jdbc_mixin.options import (
    JDBCExecuteOptions,
    JDBCFetchOptions,
)
from onetl.connection.db_connection.jdbc_mixin.options import (
    JDBCOptions as JDBCMixinOptions,
)
from onetl.hooks import slot, support_hooks
from onetl.impl import GenericOptions
from onetl.log import log_lines

if TYPE_CHECKING:
    from pyspark.sql import DataFrame, SparkSession

log = logging.getLogger(__name__)

T = TypeVar("T")

# options generated by JDBCMixin methods
PROHIBITED_OPTIONS = frozenset(
    (
        "user",
        "password",
        "driver",
        "url",
    ),
)


class JDBCStatementType(Enum):
    GENERIC = auto()
    PREPARED = auto()
    CALL = auto()


@support_hooks
class JDBCMixin:
    """
    Compatibility layer between Python and Java SQL Module.

    Spark does not allow to execute raw SQL/DDL/DML/etc statements, so this is a workaround.
    However, some of Spark's magic is used here, for example to convert raw ResultSet to move convenient DataFrame
    """

    spark: "SparkSession" = Field(repr=False)
    user: str
    password: SecretStr

    JDBCOptions = JDBCMixinOptions
    FetchOptions = JDBCFetchOptions
    ExecuteOptions = JDBCExecuteOptions

    DRIVER: ClassVar[str]

    @property
    @abstractmethod
    def jdbc_url(self) -> str:
        """JDBC Connection URL"""

    @property
    def jdbc_params(self) -> dict:
        """JDBC Connection params"""
        return {
            "user": self.user,
            "password": self.password.get_secret_value() if self.password is not None else "",
            "driver": self.DRIVER,
            "url": self.jdbc_url,
        }

    @slot
    def close(self):
        """
        Close all connections, opened by `.fetch()`, `.execute()` or `.check()` methods. [![support hooks](https://img.shields.io/badge/%20-support%20hooks-blue)](/hooks/)

        !!! warning "Deprecated since 0.13.0"
            Connections are now closed immediately. Method is now no-op.

        !!! note

            Connection can be used again after it was closed.

        Returns
        -------
        Self
            Connection itself.

        Examples
        --------

        Read data and close connection:

        ```python
        df = connection.fetch("SELECT * FROM mytable LIMIT 10")
        connection.close()

        # or

        with connection:
            connection.execute("CREATE TABLE target_table(id NUMBER, data VARCHAR)")
            connection.execute("CREATE INDEX target_table_idx ON target_table (id)")
        ```
        """

        warnings.warn(
            "Connections are now closed immediately. Method is no-op since 0.13.0",
            UserWarning,
            stacklevel=3,
        )
        return self

    def __enter__(self):
        return self

    def __exit__(self, _exc_type, _exc_value, _traceback):
        self.close()

    @slot
    def fetch(
        self,
        query: str,
        options: JDBCFetchOptions | dict | None = None,
    ) -> "DataFrame":
        """
        **Immediately** execute SELECT statement **on Spark driver** and return in-memory DataFrame. [![support hooks](https://img.shields.io/badge/%20-support%20hooks-blue)](/hooks/)

        Works almost the same like [sql][], but Spark executor is not used.

        !!! note

            Statement is executed in read-only connection, so it should not change any data in the database.
            However, behavior may depend on RDBMS type and JDBC driver options.

        !!! success "Added in 0.2.0"

        Parameters
        ----------
        query : str

            SQL query to be executed.

        options : dict, [FetchOptions][], optional

            Options to be passed directly to JDBC driver, like `fetchsize` or `queryTimeout`

            !!! note

                You cannot use [ReadOptions][], they are handled by Spark, not by JDBC driver itself

        Returns
        -------
        df : pyspark.sql.dataframe.DataFrame

            Spark dataframe
        """

        query = clear_statement(query)

        log.info("|%s| Detected dialect: '%s'", self.__class__.__name__, self._get_spark_dialect_class_name())
        log.info("|%s| Executing SQL query (on driver):", self.__class__.__name__)
        log_lines(log, query)

        call_options = (
            self.FetchOptions.parse(options.dict())
            if isinstance(options, JDBCMixinOptions)
            else self.FetchOptions.parse(options)
        )

        with override_job_description(self.spark, f"{self}.fetch()"):
            started = time.perf_counter()
            try:
                df, rows_count = self._query_with_count_on_driver(query, call_options)
            except Exception:
                elapsed = naturaldelta(time.perf_counter() - started, minimum_unit="milliseconds")
                log.exception("|%s| Query failed after %s!", self.__class__.__name__, elapsed)
                raise

            elapsed = naturaldelta(time.perf_counter() - started, minimum_unit="milliseconds")
            log.info("|%s| Query succeeded, created in-memory dataframe in %s", self.__class__.__name__, elapsed)

            # as we don't actually use Spark for this method, SparkMetricsRecorder is useless.
            # Just create metrics by hand, and fill them up using information based on dataframe content.
            metrics = SparkCommandMetrics()
            metrics.input.read_rows = rows_count
            metrics.driver.in_memory_bytes = estimate_dataframe_size(df)
            log.info("|%s| Recorded metrics:", self.__class__.__name__)
            log_lines(log, str(metrics))
        return df

    @slot
    def execute(
        self,
        statement: str,
        options: JDBCExecuteOptions | dict | None = None,
    ) -> "DataFrame | None":
        """
        **Immediately** execute DDL, DML or procedure/function **on Spark driver**. [![support hooks](https://img.shields.io/badge/%20-support%20hooks-blue)](/hooks/)

        There is no method like this in `pyspark.sql.SparkSession` object,
        but Spark internal methods works almost the same (but on executor side).

        !!! success "Added in 0.2.0"

        Parameters
        ----------
        statement : str

            Statement to be executed.

        options : dict, [JDBCExecuteOptions][], optional

            Options to be passed directly to JDBC driver, like `queryTimeout`

            !!! note

                You cannot use [WriteOptions][], they are handled by Spark, not by JDBC driver itself

        Returns
        -------
        df : pyspark.sql.dataframe.DataFrame, optional

            Spark DataFrame.

            DataFrame is returned only if input is DML statement with `RETURNING ...` clause,
            or a procedure/function call. In other cases returns `None`.
        """

        statement = clear_statement(statement)

        log.info("|%s| Detected dialect: '%s'", self.__class__.__name__, self._get_spark_dialect_class_name())
        log.info("|%s| Executing statement (on driver):", self.__class__.__name__)
        log_lines(log, statement)

        call_options = (
            self.ExecuteOptions.parse(options.dict())
            if isinstance(options, JDBCMixinOptions)
            else self.ExecuteOptions.parse(options)
        )

        with override_job_description(self.spark, f"{self}.execute()"):
            started = time.perf_counter()
            try:
                df, rows_count = self._call_with_count_on_driver(statement, call_options)
            except Exception:
                elapsed = naturaldelta(time.perf_counter() - started, minimum_unit="milliseconds")
                log.exception("|%s| Execution failed after %s!", self.__class__.__name__, elapsed)
                raise

            elapsed = naturaldelta(time.perf_counter() - started, minimum_unit="milliseconds")
            if not df:
                log.info("|%s| Execution succeeded in %s, nothing returned", self.__class__.__name__, elapsed)
                return None

            log.info("|%s| Execution succeeded, created in-memory dataframe in %s", self.__class__.__name__, elapsed)
            # as we don't actually use Spark for this method, SparkMetricsRecorder is useless.
            # Just create metrics by hand, and fill them up using information based on dataframe content.
            metrics = SparkCommandMetrics()
            metrics.input.read_rows = rows_count
            metrics.driver.in_memory_bytes = estimate_dataframe_size(df)

            log.info("|%s| Recorded metrics:", self.__class__.__name__)
            log_lines(log, str(metrics))
        return df

    def _query_on_driver(
        self,
        query: str,
        options: JDBCFetchOptions | JDBCExecuteOptions,
    ) -> "DataFrame":
        return self._query_with_count_on_driver(query, options)[0]

    def _query_with_count_on_driver(
        self,
        query: str,
        options: JDBCFetchOptions | JDBCExecuteOptions,
    ) -> "tuple[DataFrame, int]":
        return self._execute_on_driver(
            statement=query,
            statement_type=JDBCStatementType.PREPARED,
            callback=self._statement_to_dataframe,
            options=options,
            read_only=True,
        )

    def _query_optional_on_driver(
        self,
        query: str,
        options: JDBCFetchOptions,
    ) -> "DataFrame | None":
        return self._query_optional_with_count_on_driver(query, options)[0]

    def _query_optional_with_count_on_driver(
        self,
        query: str,
        options: JDBCFetchOptions,
    ) -> "tuple[DataFrame | None, int]":
        return self._execute_on_driver(
            statement=query,
            statement_type=JDBCStatementType.PREPARED,
            callback=self._statement_to_optional_dataframe,
            options=options,
            read_only=True,
        )

    def _call_on_driver(
        self,
        query: str,
        options: JDBCExecuteOptions,
    ) -> "DataFrame | None":
        return self._call_with_count_on_driver(query, options)[0]

    def _call_with_count_on_driver(
        self,
        query: str,
        options: JDBCExecuteOptions,
    ) -> "tuple[DataFrame | None, int]":
        return self._execute_on_driver(
            statement=query,
            statement_type=JDBCStatementType.CALL,
            callback=self._statement_to_optional_dataframe,
            options=options,
            read_only=False,
        )

    def _get_jdbc_properties(
        self,
        options: GenericOptions,
        **kwargs,
    ) -> dict[str, str]:
        """
        Fills up human-readable Options class to a format required by Spark internal methods
        """
        result = self.jdbc_params
        result.update(options.dict(by_alias=True, **kwargs))
        return stringify(result)

    def _options_to_connection_properties(self, options: JDBCFetchOptions | JDBCExecuteOptions):
        """
        Converts human-readable Options class to `java.util.Properties`.

        Spark's internal class `JDBCOptions` already contains all the magic we need.

        See:
        * https://github.com/apache/spark/blob/v3.2.0/sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/jdbc/JDBCOptions.scala#L237
        * https://github.com/apache/spark/blob/v3.2.0/sql/core/src/main/scala/org/apache/spark/sql/DataFrameReader.scala#L288-L295
        """

        jdbc_properties = self._get_jdbc_properties(options, exclude_none=True)
        jvm = self.spark._jvm  # type: ignore[attr-defined]  # noqa: SLF001
        JdbcUtils = jvm.org.apache.spark.sql.execution.datasources.jdbc  # type: ignore[union-attr]  # noqa: N806
        jdbc_options = JdbcUtils.JDBCOptions(
            self.jdbc_url,
            # JDBCOptions class requires `table` argument to be passed, but it is not used in asConnectionProperties
            "table",
            jvm.PythonUtils.toScalaMap(jdbc_properties),  # type: ignore[union-attr]
        )
        return jdbc_options.asConnectionProperties()

    def _get_jdbc_connection(
        self,
        options: JDBCFetchOptions | JDBCExecuteOptions,
        *,
        read_only: bool,
    ):
        connection_properties = self._options_to_connection_properties(options)
        jvm = self.spark._jvm  # type: ignore[attr-defined]  # noqa: SLF001
        connection = jvm.java.sql.DriverManager.getConnection(self.jdbc_url, connection_properties)  # type: ignore[union-attr]
        connection.setReadOnly(read_only)
        return connection

    def _get_spark_dialect_class_name(self) -> str:
        """
        Returns the name of the JDBC dialect associated with the connection URL.
        """
        from py4j.java_gateway import JavaObject

        dialect = self._get_spark_dialect()
        if isinstance(dialect, JavaObject):
            dialect = dialect.getClass()
        return dialect.getCanonicalName().split("$")[0]

    def _get_spark_dialect(self):
        jvm = self.spark._jvm  # type: ignore[attr-defined]  # noqa: SLF001
        return jvm.org.apache.spark.sql.jdbc.JdbcDialects.get(self.jdbc_url)

    def _get_statement_args(self) -> tuple[int, ...]:
        resultset = self.spark._jvm.java.sql.ResultSet  # type: ignore[attr-defined, union-attr]  # noqa: SLF001
        return resultset.TYPE_FORWARD_ONLY, resultset.CONCUR_READ_ONLY

    def _execute_on_driver(
        self,
        statement: str,
        statement_type: JDBCStatementType,
        callback: Callable[..., T],
        options: JDBCFetchOptions | JDBCExecuteOptions,
        read_only: bool,  # noqa: FBT001
    ) -> T:
        """
        Actually execute statement on driver.

        Almost like `org.apache.spark.sql.execution.datasources.jdbc.JDBCRDD` is fetching data:
        * https://github.com/apache/spark/blob/v3.2.0/sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/jdbc/JDBCRDD.scala#L352-L363

        Each time new connection is opened to execute the statement, and then closed.
        """

        statement_args = self._get_statement_args()
        jdbc_connection = self._get_jdbc_connection(options, read_only=read_only)
        with closing(jdbc_connection):
            jdbc_statement = self._build_statement(statement, statement_type, jdbc_connection, statement_args)
            return self._execute_statement(jdbc_connection, jdbc_statement, statement, options, callback, read_only)

    def _execute_statement(  # noqa: PLR0913, PLR0917
        self,
        jdbc_connection,
        jdbc_statement,
        statement: str,
        options: JDBCFetchOptions | JDBCExecuteOptions,
        callback: Callable[..., T],
        read_only: bool,  # noqa: FBT001
    ) -> T:
        """
        Executes `java.sql.Statement` or child class and passes it into the callback function.

        See:
        * https://github.com/apache/spark/blob/v3.2.0/sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/jdbc/JdbcUtils.scala#L261-L264
        * https://github.com/apache/spark/blob/v3.2.0/sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/jdbc/JDBCRDD.scala#L354-L358
        * https://github.com/apache/spark/blob/v3.2.0/sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/jdbc/JdbcUtils.scala#L111
        """
        from py4j.java_gateway import is_instance_of

        gateway = get_java_gateway(self.spark)
        jvm = self.spark._jvm  # type: ignore[attr-defined]  # noqa: SLF001

        is_prepared = is_instance_of(gateway, jdbc_statement, jvm.java.sql.PreparedStatement)  # type: ignore[union-attr]
        is_callable = is_instance_of(gateway, jdbc_statement, jvm.java.sql.CallableStatement)  # type: ignore[union-attr]

        with closing(jdbc_statement):
            if options.fetchsize is not None:
                jdbc_statement.setFetchSize(options.fetchsize)

            if options.query_timeout is not None:
                jdbc_statement.setQueryTimeout(options.query_timeout)

            # Java SQL classes are not consistent..
            if is_prepared or is_callable:
                jdbc_statement.execute()
            elif read_only:
                jdbc_statement.executeQuery(statement)
            else:
                jdbc_statement.executeUpdate(statement)

            return callback(jdbc_connection, jdbc_statement)

    @staticmethod
    def _build_statement(
        statement: str,
        statement_type: JDBCStatementType,
        jdbc_connection,
        statement_args,
    ):
        """
        Builds `java.sql.Statement`, `java.sql.PreparedStatement` or `java.sql.CallableStatement`,
        depending on `statement_type` argument value.

        Raw `java.sql.Statement` does not support some features provided by db driver, like `{call ...}` syntax.
        This is handled by `java.sql.PreparedStatement` or `java.sql.CallableStatement`.

        See:
        * https://github.com/apache/spark/blob/v3.2.0/sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/jdbc/JDBCRDD.scala#L354-L355
        * https://github.com/apache/spark/blob/v3.2.0/sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/jdbc/JdbcUtils.scala#L698
        """

        if statement_type == JDBCStatementType.PREPARED:
            return jdbc_connection.prepareStatement(statement, *statement_args)

        if statement_type == JDBCStatementType.CALL:
            return jdbc_connection.prepareCall(statement, *statement_args)

        return jdbc_connection.createStatement(*statement_args)

    def _statement_to_dataframe(self, jdbc_connection, jdbc_statement) -> "tuple[DataFrame, int]":
        result_set = jdbc_statement.getResultSet()
        return self._resultset_with_count_to_dataframe(jdbc_connection, result_set)

    def _statement_to_optional_dataframe(self, jdbc_connection, jdbc_statement) -> "tuple[DataFrame | None, int]":
        """
        Returns `org.apache.spark.sql.DataFrame` or `None`, if ResultSet is does not contain any columns.

        DDL or DML statement without `RETURNING` clause usually do not return anything.
        """

        result_set = jdbc_statement.getResultSet()

        if not result_set or result_set.isClosed():
            return None, 0

        result_metadata = result_set.getMetaData()
        result_column_count = result_metadata.getColumnCount()
        if not result_column_count:
            return None, 0

        return self._resultset_with_count_to_dataframe(jdbc_connection, result_set)

    def _resultset_with_count_to_dataframe(self, jdbc_connection, result_set) -> "tuple[DataFrame, int]":
        """
        Converts `java.sql.ResultSet` to `org.apache.spark.sql.DataFrame` using Spark's internal methods.

        That's almost exactly like Spark is fetching the data, but on driver.

        See:
        * https://github.com/apache/spark/blob/v3.2.0/sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/jdbc/JDBCRDD.scala#L352-L359
        * https://github.com/apache/spark/blob/v3.2.0/sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/jdbc/JdbcUtils.scala#L337-L343
        """

        from pyspark.sql import DataFrame

        jdbc_dialect = self._get_spark_dialect()
        jvm = self.spark._jvm  # type: ignore[attr-defined]  # noqa: SLF001
        JdbcUtils = jvm.org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils  # type: ignore[union-attr]  # noqa: N806
        JavaConverters = jvm.scala.collection.JavaConverters  # type: ignore[union-attr]  # noqa: N806

        spark_version = get_spark_version(self.spark)

        if spark_version >= Version("4.0"):
            result_schema = JdbcUtils.getSchema(
                jdbc_connection,
                result_set,
                jdbc_dialect,
                False,  # noqa: FBT003
                False,  # noqa: FBT003
            )
        elif spark_version >= Version("3.4"):
            # https://github.com/apache/spark/commit/2349175e1b81b0a61e1ed90c2d051c01cf78de9b
            result_schema = JdbcUtils.getSchema(result_set, jdbc_dialect, False, False)  # noqa: FBT003
        else:
            result_schema = JdbcUtils.getSchema(result_set, jdbc_dialect, False)  # noqa: FBT003

        if spark_version.major >= 4:  # noqa: PLR2004
            result_iterator = JdbcUtils.resultSetToRows(result_set, result_schema, jdbc_dialect)
        else:
            result_iterator = JdbcUtils.resultSetToRows(result_set, result_schema)

        result_list = JavaConverters.seqAsJavaListConverter(result_iterator.toSeq()).asJava()
        rows_count = result_list.size()
        jdf = self.spark._jsparkSession.createDataFrame(result_list, result_schema)  # type: ignore[attr-defined]  # noqa: SLF001

        # But since Spark 3.3 "_wrapped" attribute was removed from SparkSession
        spark_context = getattr(self.spark, "_wrapped", self.spark)

        return DataFrame(jdf, spark_context), rows_count
