# SPDX-FileCopyrightText: 2023-present MTS PJSC
# SPDX-License-Identifier: Apache-2.0
import sys

from pydantic import ConfigDict, Field

from onetl.impl import GenericOptions

if sys.version_info >= (3, 13):
    from warnings import deprecated
else:
    from typing_extensions import deprecated

# options generated by JDBCMixin methods
PROHIBITED_OPTIONS = frozenset(
    (
        "user",
        "password",
        "driver",
        "url",
    ),
)


@deprecated("Deprecated in 0.11.0 and will be removed in 1.0.0. Use FetchOptions or ExecuteOptions instead")
class JDBCOptions(GenericOptions):
    """Generic options, related to specific JDBC driver.

    !!! warning "Deprecated since 0.11.0"
        Use `SomeDB.FetchOptions` or `SomeDB.ExecuteOptions` instead

    Examples
    --------

    !!! note

        You can pass any value supported by underlying JDBC driver class,
        even if it is not mentioned in this documentation.

    ```python
    from onetl.connection import SomeDB

    options = SomeDB.Options(
        queryTimeout=60_000,
        fetchsize=100_000,
        customSparkOption="value",
    )
    ```
    """

    model_config = ConfigDict(prohibited_options=PROHIBITED_OPTIONS, extra="allow")  # type: ignore[typeddict-unknown-key]

    query_timeout: int | None = Field(default=None, alias="queryTimeout")
    """The number of seconds the driver will wait for a statement to execute.
    Zero means there is no limit.

    This option depends on driver implementation,
    some drivers can check the timeout of each query instead of an entire JDBC batch.
    """

    fetchsize: int | None = None
    """How many rows to fetch per round trip.

    Tuning this option can influence performance of reading.

    !!! warning

        Default value depends on driver. For example, Oracle has
        default `fetchsize=10`.
    """


class JDBCFetchOptions(GenericOptions):
    """Options related to fetching data from databases via JDBC.

    !!! success "Added in 0.11.0"
        Replace `SomeDB.JDBCOptions` → `SomeDB.FetchOptions`

    Examples
    --------

    !!! note

        You can pass any value supported by underlying JDBC driver class,
        even if it is not mentioned in this documentation.

    ```python
    from onetl.connection import SomeDB

    options = SomeDB.FetchOptions(
        queryTimeout=60_000,
        fetchsize=100_000,
        customSparkOption="value",
    )
    ```
    """

    model_config = ConfigDict(prohibited_options=PROHIBITED_OPTIONS, extra="allow")  # type: ignore[typeddict-unknown-key]

    query_timeout: int | None = Field(default=None, alias="queryTimeout")
    """The number of seconds the driver will wait for a statement to execute.
    Zero means there is no limit.

    This option depends on driver implementation,
    some drivers can check the timeout of each query instead of an entire JDBC batch.
    """

    fetchsize: int | None = None
    """How many rows to fetch per round trip.

    Tuning this option can influence performance of reading.

    !!! warning
        Default value depends on driver. For example, Oracle has
        default `fetchsize=10`.
    """


class JDBCExecuteOptions(GenericOptions):
    """Options related to executing statements in databases via JDBC.

    !!! success "Added in 0.11.0"
        Replace `SomeDB.JDBCOptions` → `SomeDB.ExecuteOptions`

    Examples
    --------

    !!! note

        You can pass any value supported by underlying JDBC driver class,
        even if it is not mentioned in this documentation.

    ```python
    from onetl.connection import SomeDB

    options = SomeDB.ExecuteOptions(
        queryTimeout=60_000,
        customSparkOption="value",
    )
    ```
    """

    model_config = ConfigDict(prohibited_options=PROHIBITED_OPTIONS, extra="allow")  # type: ignore[typeddict-unknown-key]

    query_timeout: int | None = Field(default=None, alias="queryTimeout")
    """The number of seconds the driver will wait for a statement to execute.
    Zero means there is no limit.

    This option depends on driver implementation,
    some drivers can check the timeout of each query instead of an entire JDBC batch.
    """

    fetchsize: int | None = None
    """How many rows to fetch per round trip.

    Tuning this option can influence performance of reading.

    !!! warning
        Default value depends on driver. For example, Oracle has
        default `fetchsize=10`.
    """
