site_name: onETL Docs

theme:
  name: material
  features:
    - navigation.indexes
    - content.tabs.link
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night 
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  locale: ru
  highlightjs: true
  hljs_languages:
    - yaml

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.critic
  - mdx_gh_links
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format  

extension_configs:
  - mdx_gh_links:
    - user: "foo"
    - repo: "bar"

nav:
  - Test: changelog/0.7.0.md