name: Release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

env:
  DEFAULT_PYTHON: '3.13'

jobs:
  release:
    name: Release package
    runs-on: ubuntu-latest
    if: github.repository == 'MTSWebServices/onetl'  # prevent running on forks

    environment:
      name: pypi
      url: https://pypi.org/p/onetl

    permissions:
      id-token: write # to auth in PyPI
      contents: write # to create Github release

    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Patch version template
        # Due to change above, git stage area is dirty, so we need to patch the template
        run: sed -i 's#dirty_template = ".*"#dirty_template = "{tag}"#' pyproject.toml

      - name: Fix logo in Readme
        run: |
          sed -i "s#image:: mddocs/docs/#image:: https://raw.githubusercontent.com/MTSWebServices/onetl/$GITHUB_SHA/mddocs/docs/#g" README.rst

      - name: Set up Python ${{ env.DEFAULT_PYTHON }}
        id: python
        uses: actions/setup-python@v7
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: 'false'

      - name: Build package
        run: uv build

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1

      - name: Prepare changelog
        run: |
          cat mddocs/docs/changelog/${GITHUB_REF_NAME}.md > changelog.md
          # Remove anchors like "{ #DBR-onetl-changelog-0-7-0 }"
          sed -i -E 's/\{.*\}//g' changelog.md
          # Header looks like "# 0.7.0 (2023-05-15)"
          # Release name looks like "0.7.0 (2023-05-15)"
          echo -n name= > "$GITHUB_OUTPUT"
          cat changelog.md | head -1 | sed -E "s/#+\s*//g" >> "$GITHUB_OUTPUT"
          # Remove header with release name
          sed -i -e '1,2d' changelog.md

      - name: Create Github release
        id: create_release
        uses: softprops/action-gh-release@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: false
          name: ${{ steps.release-name.outputs.name }}
          body_path: changelog.md
          files: |
            dist/*.tar.gz
            dist/*.whl
