name: Repo labels sync

on:
  push:
    branches:
      - develop
    paths:
      - .github/labels.yml
      - .github/workflows/repo-labels-sync.yml
  pull_request:
    paths:
      - .github/labels.yml
      - .github/workflows/repo-labels-sync.yml

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Labeler
        uses: crazy-max/ghaction-github-labeler@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          yaml-file: .github/labels.yml
          dry-run: ${{ github.event_name == 'pull_request' }}
