name: Tests for core
on:
  workflow_call:
    inputs:
      spark-version:
        required: true
        type: string
      etl-entities-version:
        required: true
        type: string
      java-version:
        required: true
        type: string
      python-version:
        required: true
        type: string
      os:
        required: true
        type: string
      with-cache:
        required: false
        type: boolean
        default: true

jobs:
  test-core:
    name: Run core tests (spark=${{ inputs.spark-version }}, etl-entities=${{ inputs.etl-entities-version }}, java=${{ inputs.java-version }}, python=${{ inputs.python-version }}, os=${{ inputs.os }})
    runs-on: ${{ inputs.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v7
        with:
          python-version: ${{ inputs.python-version }}

      - name: Set up Java ${{ inputs.java-version }}
        uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: ${{ inputs.java-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          activate-environment: 'true'
          enable-cache: 'false'

      # astral-sh/setup-uv cannot restore multiple keys
      - name: Cache uv
        uses: actions/cache/restore@v6
        with:
          path: ~/.cache/uv
          key: ${{ runner.os }}-python${{ inputs.python-version }}-etl-entities${{ inputs.etl-entities-version}}-spark${{ inputs.spark-version }}-${{ hashFiles('uv.lock') }}
          restore-keys: |
            ${{ runner.os }}-python${{ inputs.python-version }}-etl-entities${{ inputs.etl-entities-version}}-spark${{ inputs.spark-version }}-${{ hashFiles('uv.lock') }}
            ${{ runner.os }}-python${{ inputs.python-version }}-etl-entities${{ inputs.etl-entities-version}}-spark${{ inputs.spark-version }}-
            ${{ runner.os }}-python${{ inputs.python-version }}-etl-entities${{ inputs.etl-entities-version}}-
            ${{ runner.os }}-python${{ inputs.python-version }}-

      - name: Run tests
        run: |
          export "PYTEST=coverage run -m pytest --junitxml=reports/junit/core-${RANDOM}.xml"
          make test-core
          export "PYTEST=coverage run -m pytest --junitxml=reports/junit/doctest-${RANDOM}.xml"
          make test-doctest
        env:
          ETL_ENTITIES_VERSION: ${{ inputs.etl-entities-version }}
          SPARK_VERSION: ${{ inputs.spark-version }}

      - name: Upload coverage results
        if: success() || failure()
        uses: actions/upload-artifact@v7
        with:
          name: coverage-core-spark${{ inputs.spark-version }}-python-${{ inputs.python-version }}
          path: reports/*
          # https://github.com/actions/upload-artifact/issues/602
          include-hidden-files: true
