name: Tests for Greenplum
on:
  workflow_call:
    inputs:
      greenplum-version:
        required: true
        type: string
      package-version:
        required: true
        type: string
      spark-version:
        required: true
        type: string
      etl-entities-version:
        required: true
        type: string
      java-version:
        required: true
        type: string
      python-version:
        required: true
        type: string
      os:
        required: true
        type: string
      with-cache:
        required: false
        type: boolean
        default: true
    secrets:
      GREENPLUM_PACKAGES_USER:
        required: true
      GREENPLUM_PACKAGES_PASSWORD:
        required: true

jobs:
  test-greenplum:
    if: github.repository == 'MTSWebServices/onetl'  # prevent running on forks
    name: Run Greenplum tests (server=${{ inputs.greenplum-version }}, spark=${{ inputs.spark-version }}, etl-entities=${{ inputs.etl-entities-version }}, java=${{ inputs.java-version }}, python=${{ inputs.python-version }}, os=${{ inputs.os }})
    runs-on: ${{ inputs.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Start Grenplum
        run: |
          docker compose --profile all down -v --remove-orphans
          docker compose --profile greenplum up -d --pull always
        env:
          GREENPLUM_IMAGE: andruche/greenplum:${{ inputs.greenplum-version }}

      - name: Set up Java ${{ inputs.java-version }}
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: ${{ inputs.java-version }}

      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v7
        with:
          python-version: ${{ inputs.python-version }}

      # no caching of ~/.ivy2 because Greenplum connector is just a few MB

      - name: Set up Postgres client
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends postgresql-client

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          activate-environment: 'true'
          enable-cache: 'false'

      # astral-sh/setup-uv cannot restore multiple keys
      - name: Cache uv
        uses: actions/cache/restore@v6
        with:
          path: ~/.cache/uv
          key: ${{ runner.os }}-python${{ inputs.python-version }}-etl-entities${{ inputs.etl-entities-version}}-spark${{ inputs.spark-version }}-${{ hashFiles('uv.lock') }}
          restore-keys: |
            ${{ runner.os }}-python${{ inputs.python-version }}-etl-entities${{ inputs.etl-entities-version}}-spark${{ inputs.spark-version }}-${{ hashFiles('uv.lock') }}
            ${{ runner.os }}-python${{ inputs.python-version }}-etl-entities${{ inputs.etl-entities-version}}-spark${{ inputs.spark-version }}-
            ${{ runner.os }}-python${{ inputs.python-version }}-etl-entities${{ inputs.etl-entities-version}}-
            ${{ runner.os }}-python${{ inputs.python-version }}-

      - name: Wait for Grenplum to be ready
        run: |
          docker compose --profile greenplum up -d --wait --wait-timeout 200
        env:
          GREENPLUM_IMAGE: andruche/greenplum:${{ inputs.greenplum-version }}

      - name: Run tests
        run: |
          mkdir reports/ || echo "Directory exists"
          export "PYTEST=coverage run -m pytest --junitxml=reports/junit/greenplum-${RANDOM}.xml"
          make test-spark UV_ARGS="--group test-greenplum" PYTEST_ARGS="-m greenplum"
        env:
          ETL_ENTITIES_VERSION: ${{ inputs.etl-entities-version }}
          SPARK_VERSION: ${{ inputs.spark-version }}
          ONETL_GP_PACKAGE_VERSION: ${{ inputs.package-version }}
          GREENPLUM_PACKAGES_USER: ${{ secrets.GREENPLUM_PACKAGES_USER }}
          GREENPLUM_PACKAGES_PASSWORD: ${{ secrets.GREENPLUM_PACKAGES_PASSWORD }}

      - name: Run tests with PGBouncer
        run: |
          mkdir reports/ || echo "Directory exists"
          export "PYTEST=coverage run -m pytest --junitxml=reports/junit/greenplum-pgbouncer-${RANDOM}.xml"
          make test-spark UV_ARGS="--group test-greenplum" PYTEST_ARGS="-m greenplum -k 'tests_core_integration or tests_db_connection_integration'"
        env:
          ETL_ENTITIES_VERSION: ${{ inputs.etl-entities-version }}
          SPARK_VERSION: ${{ inputs.spark-version }}
          ONETL_GP_PACKAGE_VERSION: ${{ inputs.package-version }}
          ONETL_GP_PORT: 6433
          GREENPLUM_PACKAGES_USER: ${{ secrets.GREENPLUM_PACKAGES_USER }}
          GREENPLUM_PACKAGES_PASSWORD: ${{ secrets.GREENPLUM_PACKAGES_PASSWORD }}

      - name: Dump Greenplum logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v2
        with:
          images: andruche/greenplum,bitnamilegacy/pgbouncer
          dest: ./logs

      - name: Upload Greenplum logs
        uses: actions/upload-artifact@v7
        if: failure()
        with:
          name: container-logs-greenplum-${{ inputs.greenplum-version }}-spark${{ inputs.spark-version }}
          path: logs/*

      - name: Shutdown Greenplum
        if: always()
        run: |
          docker compose --profile all down -v --remove-orphans

      - name: Upload coverage results
        if: success() || failure()
        uses: actions/upload-artifact@v7
        with:
          name: coverage-greenplum-${{ inputs.greenplum-version }}-spark${{ inputs.spark-version }}
          path: reports/*
          # https://github.com/actions/upload-artifact/issues/602
          include-hidden-files: true
          overwrite: true
