name: Tests for FTP
on:
  workflow_call:
    inputs:
      ftp-version:
        required: true
        type: string
      pydantic-version:
        required: true
        type: string
      etl-entities-version:
        required: true
        type: string
      python-version:
        required: true
        type: string
      os:
        required: true
        type: string
      with-cache:
        required: false
        type: boolean
        default: true

jobs:
  test-ftp:
    name: Run FTP tests (server=${{ inputs.ftp-version }}, pydantic=${{ inputs.pydantic-version }}, python=${{ inputs.python-version }}, os=${{ inputs.os }})
    runs-on: ${{ inputs.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Start FTP
        run: |
          docker compose --profile all down -v --remove-orphans
          docker compose --profile ftp up -d --pull always
        env:
          FTP_IMAGE: chonjay21/ftps:${{ inputs.ftp-version }}

      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v7
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          activate-environment: 'true'
          enable-cache: 'false'

      # no uv cache here because fresh install takes about 1 second

      - name: Wait for FTP to be ready
        run: |
          docker compose --profile ftp up -d --wait --wait-timeout 200
        env:
          FTP_IMAGE: chonjay21/ftps:${{ inputs.ftp-version }}

      - name: Run tests
        run: |
          mkdir reports/ || echo "Directory exists"
          export "PYTEST=coverage run -m pytest --junitxml=reports/junit/ftp-${RANDOM}.xml"
          make test-no-spark UV_ARGS="--extra ftp" PYTEST_ARGS="-m ftp"
        env:
          PYDANTIC_VERSION: ${{ inputs.pydantic-version }}
          ETL_ENTITIES_VERSION: ${{ inputs.etl-entities-version }}

      - name: Dump FTP logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v2
        with:
          images: chonjay21/ftps
          dest: ./logs

      - name: Upload FTP logs
        uses: actions/upload-artifact@v7
        if: failure()
        with:
          name: container-logs-ftp-${{ inputs.ftp-version }}-python-${{ inputs.python-version }}
          path: logs/*
          # https://github.com/actions/upload-artifact/issues/602
          include-hidden-files: true

      - name: Shutdown FTP
        if: always()
        run: |
          docker compose --profile all down -v --remove-orphans

      - name: Upload coverage results
        if: success() || failure()
        uses: actions/upload-artifact@v7
        with:
          name: coverage-ftp-${{ inputs.ftp-version }}-python-${{ inputs.python-version }}
          path: reports/*
          # https://github.com/actions/upload-artifact/issues/602
          include-hidden-files: true
