name: Tests for Postgres
on:
  workflow_call:
    inputs:
      postgres-version:
        required: true
        type: string
      spark-version:
        required: true
        type: string
      etl-entities-version:
        required: true
        type: string
      java-version:
        required: true
        type: string
      python-version:
        required: true
        type: string
      os:
        required: true
        type: string
      with-cache:
        required: false
        type: boolean
        default: true

jobs:
  test-postgres:
    name: Run Postgres tests (server=${{ inputs.postgres-version }}, spark=${{ inputs.spark-version }}, etl-entities=${{ inputs.etl-entities-version }}, java=${{ inputs.java-version }}, python=${{ inputs.python-version }}, os=${{ inputs.os }})
    runs-on: ${{ inputs.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Start Postgres
        run: |
          docker compose --profile all down -v --remove-orphans
          docker compose --profile postgres up -d --pull always
        env:
          POSTGRES_IMAGE: postgres:${{ inputs.postgres-version }}

      - name: Set up Java ${{ inputs.java-version }}
        uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: ${{ inputs.java-version }}

      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v7
        with:
          python-version: ${{ inputs.python-version }}

      # no caching of ~/.ivy2 because Postgres JDBC driver is just a few MB

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          activate-environment: 'true'
          enable-cache: 'false'

      # astral-sh/setup-uv cannot restore multiple keys
      - name: Cache uv
        uses: actions/cache/restore@v6
        with:
          path: ~/.cache/uv
          key: ${{ runner.os }}-python${{ inputs.python-version }}-etl-entities${{ inputs.etl-entities-version}}-spark${{ inputs.spark-version }}-${{ hashFiles('uv.lock') }}
          restore-keys: |
            ${{ runner.os }}-python${{ inputs.python-version }}-etl-entities${{ inputs.etl-entities-version}}-spark${{ inputs.spark-version }}-${{ hashFiles('uv.lock') }}
            ${{ runner.os }}-python${{ inputs.python-version }}-etl-entities${{ inputs.etl-entities-version}}-spark${{ inputs.spark-version }}-
            ${{ runner.os }}-python${{ inputs.python-version }}-etl-entities${{ inputs.etl-entities-version}}-
            ${{ runner.os }}-python${{ inputs.python-version }}-

      - name: Wait for Postgres to be ready
        run: |
          docker compose --profile postgres up -d --wait --wait-timeout 200
        env:
          POSTGRES_IMAGE: postgres:${{ inputs.postgres-version }}

      - name: Run tests
        run: |
          mkdir reports/ || echo "Directory exists"
          export "PYTEST=coverage run -m pytest --junitxml=reports/junit/postgres-${RANDOM}.xml"
          make test-spark UV_ARGS="--group test-postgres" PYTEST_ARGS="-m postgres"
        env:
          ETL_ENTITIES_VERSION: ${{ inputs.etl-entities-version }}
          SPARK_VERSION: ${{ inputs.spark-version }}

      - name: Run tests with PGBouncer
        run: |
          mkdir reports/ || echo "Directory exists"
          export "PYTEST=coverage run -m pytest --junitxml=reports/junit/postgres-pgbouncer-${RANDOM}.xml"
          make test-spark UV_ARGS="--group test-postgres" PYTEST_ARGS="-m postgres -k 'tests_core_integration or tests_db_connection_integration'"
        env:
          ONETL_PG_PORT: 6432
          ETL_ENTITIES_VERSION: ${{ inputs.etl-entities-version }}
          SPARK_VERSION: ${{ inputs.spark-version }}

      - name: Dump Postgres logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v2
        with:
          images: postgres,bitnamilegacy/pgbouncer
          dest: ./logs

      - name: Upload Postgres logs
        uses: actions/upload-artifact@v7
        if: failure()
        with:
          name: container-logs-postgres-${{ inputs.postgres-version }}-spark${{ inputs.spark-version }}
          path: logs/*

      - name: Shutdown Postgres
        if: always()
        run: |
          docker compose --profile all down -v --remove-orphans

      - name: Upload coverage results
        if: success() || failure()
        uses: actions/upload-artifact@v7
        with:
          name: coverage-postgres-${{ inputs.postgres-version }}-spark${{ inputs.spark-version }}
          path: reports/*
          # https://github.com/actions/upload-artifact/issues/602
          include-hidden-files: true
