name: Tests for Samba
on:
  workflow_call:
    inputs:
      server-version:
        required: true
        type: string
      etl-entities-version:
        required: true
        type: string
      python-version:
        required: true
        type: string
      os:
        required: true
        type: string
      with-cache:
        required: false
        type: boolean
        default: true

jobs:
  test-samba:
    name: Run Samba tests (server=${{ inputs.server-version }}, etl-entities=${{ inputs.etl-entities-version }}, python=${{ inputs.python-version }}, os=${{ inputs.os }})
    runs-on: ${{ inputs.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Start Samba
        run: |
          docker compose --profile all down -v --remove-orphans
          docker compose --profile samba up -d --pull always
        env:
          SAMBA_IMAGE: elswork/samba:${{ inputs.server-version }}

      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v7
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          activate-environment: 'true'
          enable-cache: 'false'

      # no uv cache here because fresh install takes about 1 second

      - name: Wait for Samba to be ready
        run: |
          docker compose --profile samba up -d --wait --wait-timeout 200
        env:
          SAMBA_IMAGE: elswork/samba:${{ inputs.server-version }}

      - name: Run tests
        run: |
          mkdir reports/ || echo "Directory exists"
          export "PYTEST=coverage run -m pytest --junitxml=reports/junit/samba-${RANDOM}.xml"
          make test-no-spark UV_ARGS="--extra samba" PYTEST_ARGS="-m samba"
        env:
          ETL_ENTITIES_VERSION: ${{ inputs.etl-entities-version }}

      - name: Dump Samba logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v2
        with:
          images: elswork/samba
          dest: ./logs

      - name: Upload Samba logs
        uses: actions/upload-artifact@v7
        if: failure()
        with:
          name: container-logs-samba-${{ inputs.server-version }}-python-${{ inputs.python-version }}
          path: logs/*

      - name: Shutdown Samba
        if: always()
        run: |
          docker compose --profile all down -v --remove-orphans

      - name: Upload coverage results
        if: success() || failure()
        uses: actions/upload-artifact@v7
        with:
          name: coverage-samba-${{ inputs.server-version }}-python-${{ inputs.python-version }}
          path: reports/*
          # https://github.com/actions/upload-artifact/issues/602
          include-hidden-files: true
