name: Tests for MongoDB
on:
  workflow_call:
    inputs:
      mongodb-version:
        required: true
        type: string
      spark-version:
        required: true
        type: string
      etl-entities-version:
        required: true
        type: string
      java-version:
        required: true
        type: string
      python-version:
        required: true
        type: string
      os:
        required: true
        type: string
      with-cache:
        required: false
        type: boolean
        default: true

jobs:
  test-mongodb:
    name: Run MongoDB tests (server=${{ inputs.mongodb-version }}, spark=${{ inputs.spark-version }}, etl-entities=${{ inputs.etl-entities-version }}, java=${{ inputs.java-version }}, python=${{ inputs.python-version }}, os=${{ inputs.os }})
    runs-on: ${{ inputs.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Start MongoDB
        run: |
          docker compose --profile all down -v --remove-orphans
          docker compose --profile mongodb up -d --pull always
        env:
          MONGODB_IMAGE: mongo:${{ inputs.mongodb-version }}

      - name: Set up Java ${{ inputs.java-version }}
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: ${{ inputs.java-version }}

      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v7
        with:
          python-version: ${{ inputs.python-version }}

      # no caching of ~/.ivy2 because MongoDB JDBC driver is just a few MB

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          activate-environment: 'true'
          enable-cache: 'false'

      # astral-sh/setup-uv cannot restore multiple keys
      - name: Cache uv
        uses: actions/cache/restore@v6
        with:
          path: ~/.cache/uv
          key: ${{ runner.os }}-python${{ inputs.python-version }}-etl-entities${{ inputs.etl-entities-version}}-spark${{ inputs.spark-version }}-${{ hashFiles('uv.lock') }}
          restore-keys: |
            ${{ runner.os }}-python${{ inputs.python-version }}-etl-entities${{ inputs.etl-entities-version}}-spark${{ inputs.spark-version }}-${{ hashFiles('uv.lock') }}
            ${{ runner.os }}-python${{ inputs.python-version }}-etl-entities${{ inputs.etl-entities-version}}-spark${{ inputs.spark-version }}-
            ${{ runner.os }}-python${{ inputs.python-version }}-etl-entities${{ inputs.etl-entities-version}}-
            ${{ runner.os }}-python${{ inputs.python-version }}-

      - name: Wait for MongoDB to be ready
        run: |
          docker compose --profile mongodb up -d --wait --wait-timeout 200
        env:
          MONGODB_IMAGE: mongo:${{ inputs.mongodb-version }}

      - name: Run tests
        run: |
          mkdir reports/ || echo "Directory exists"
          export "PYTEST=coverage run -m pytest --junitxml=reports/junit/mongodb-${RANDOM}.xml"
          make test-spark UV_ARGS="--group test-mongodb" PYTEST_ARGS="-m mongodb"
        env:
          ETL_ENTITIES_VERSION: ${{ inputs.etl-entities-version }}
          SPARK_VERSION: ${{ inputs.spark-version }}

      - name: Dump MongoDB logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v2
        with:
          images: mongo
          dest: ./logs

      - name: Upload MongoDB logs
        uses: actions/upload-artifact@v7
        if: failure()
        with:
          name: container-logs-mongodb-${{ inputs.mongodb-version }}-spark${{ inputs.spark-version }}
          path: logs/*

      - name: Shutdown MongoDB
        if: always()
        run: |
          docker compose --profile all down -v --remove-orphans

      - name: Upload coverage results
        if: success() || failure()
        uses: actions/upload-artifact@v7
        with:
          name: coverage-mongodb-${{ inputs.mongodb-version }}-spark${{ inputs.spark-version }}
          path: reports/*
          # https://github.com/actions/upload-artifact/issues/602
          include-hidden-files: true
