name: Tests for Oracle
on:
  workflow_call:
    inputs:
      oracle-image:
        required: true
        type: string
      oracle-version:
        required: true
        type: string
      db-name:
        required: false
        type: string
        default: FREEPDB1
      spark-version:
        required: true
        type: string
      etl-entities-version:
        required: true
        type: string
      java-version:
        required: true
        type: string
      python-version:
        required: true
        type: string
      os:
        required: true
        type: string
      with-cache:
        required: false
        type: boolean
        default: true

jobs:
  test-oracle:
    name: Run Oracle tests (server=${{ inputs.oracle-version }}, spark=${{ inputs.spark-version }}, etl-entities=${{ inputs.etl-entities-version }}, java=${{ inputs.java-version }}, python=${{ inputs.python-version }}, os=${{ inputs.os }})
    runs-on: ${{ inputs.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Start Oracle
        run: |
          docker compose --profile all down -v --remove-orphans
          docker compose --profile oracle up -d --pull always
        env:
          ORACLE_IMAGE: ${{ inputs.oracle-image }}:${{ inputs.oracle-version }}

      - name: Set up Java ${{ inputs.java-version }}
        uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: ${{ inputs.java-version }}

      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v7
        with:
          python-version: ${{ inputs.python-version }}

      # no caching of ~/.ivy2 because Clickhouse JDBC driver is just a few MB

      - name: Set up Oracle instantclient
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends libaio1 || sudo apt-get install --no-install-recommends libaio1t64
          [ -f "/usr/lib/x86_64-linux-gnu/libaio.so.1t64" ] && sudo ln -s /usr/lib/x86_64-linux-gnu/libaio.so.1t64 /usr/lib/x86_64-linux-gnu/libaio.so.1
          mkdir ./tmp
          wget -P ./tmp https://download.oracle.com/otn_software/linux/instantclient/2110000/instantclient-basic-linux.x64-21.10.0.0.0dbru.zip
          mkdir -p ./oracle
          unzip ./tmp/instantclient-basic-linux.x64-21.10.0.0.0dbru.zip -d ./oracle
          rm -rf ./tmp/instantclient-basic-linux.x64-21.10.0.0.0dbru.zip

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          activate-environment: 'true'
          enable-cache: 'false'

      # astral-sh/setup-uv cannot restore multiple keys
      - name: Cache uv
        uses: actions/cache/restore@v6
        with:
          path: ~/.cache/uv
          key: ${{ runner.os }}-python${{ inputs.python-version }}-etl-entities${{ inputs.etl-entities-version}}-spark${{ inputs.spark-version }}-${{ hashFiles('uv.lock') }}
          restore-keys: |
            ${{ runner.os }}-python${{ inputs.python-version }}-etl-entities${{ inputs.etl-entities-version}}-spark${{ inputs.spark-version }}-${{ hashFiles('uv.lock') }}
            ${{ runner.os }}-python${{ inputs.python-version }}-etl-entities${{ inputs.etl-entities-version}}-spark${{ inputs.spark-version }}-
            ${{ runner.os }}-python${{ inputs.python-version }}-etl-entities${{ inputs.etl-entities-version}}-
            ${{ runner.os }}-python${{ inputs.python-version }}-

      - name: Wait for Oracle to be ready
        run: |
          docker compose --profile oracle up -d --wait --wait-timeout 200
        env:
          ORACLE_IMAGE: ${{ inputs.oracle-image }}:${{ inputs.oracle-version }}

      - name: Run tests
        uses: nick-fields/retry@v4
        with:
          timeout_minutes: 10
          retry_on: error
          max_attempts: 3
          command: |
            export ETL_ENTITIES_VERSION=${{ inputs.etl-entities-version }}
            export SPARK_VERSION=${{ inputs.spark-version }}
            export ONETL_ORA_CLIENT_PATH=$(realpath ./oracle/instantclient_21_10)
            export LD_LIBRARY_PATH=${ONETL_ORA_CLIENT_PATH}:${LD_LIBRARY_PATH}
            export PATH=${ONETL_ORA_CLIENT_PATH}:${PATH}
            sed -i 's|ONETL_ORA_SERVICE_NAME=.*|ONETL_ORA_SERVICE_NAME=${{ inputs.db-name }}|' .env.local

            mkdir reports/ || echo "Directory exists"
            rm -rf reports/*
            export "PYTEST=coverage run -m pytest --junitxml=reports/junit/oracle-${RANDOM}.xml"
            make test-spark UV_ARGS="--group test-oracle" PYTEST_ARGS="-m oracle"

      - name: Dump Oracle logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v2
        with:
          images: ${{ inputs.oracle-image }}
          dest: ./logs

      - name: Upload Oracle logs
        uses: actions/upload-artifact@v7
        if: failure()
        with:
          name: container-logs-oracle-${{ inputs.oracle-version }}-spark${{ inputs.spark-version }}
          path: logs/*

      - name: Shutdown Oracle
        if: always()
        run: |
          docker compose --profile all down -v --remove-orphans

      - name: Upload coverage results
        if: success() || failure()
        uses: actions/upload-artifact@v7
        with:
          name: coverage-oracle-${{ inputs.oracle-version }}-spark${{ inputs.spark-version }}
          path: reports/*
          # https://github.com/actions/upload-artifact/issues/602
          include-hidden-files: true
